language: php

notifications:
  on_success: never
  on_failure: change

php:
  - 5.4
  - 5.5

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.5
      env: WP_VERSION=2.0.4 WP_MULTISITE=0
    - php: 5.5
      env: WP_VERSION=4.0 WP_MULTISITE=0


before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit
